#!/bin/bash

date=$(date +"%d.%m.%Y")
day=$(date +"%A")
time=$(date +"%H:%M")
notify-send --app-name=mynotif " " "<span size='x-large'>$time</span><span size='medium'>\n $day</span><span size='large'> \n $date</span>" 
