#!/bin/bash

state=$( xinput list-props "Clearly Superior Technologies. CST Laser Trackball" | grep "libinput Button Scrolling Button (" | cut -f3 )

if [ $state -eq 2 ] 
then
    xinput --set-prop "Clearly Superior Technologies. CST Laser Trackball" "libinput Button Scrolling Button" 3
else
    xinput --set-prop "Clearly Superior Technologies. CST Laser Trackball" "libinput Button Scrolling Button" 2
fi
